// 카페 상세 정보 불러오기
export const LOAD_CAFE_DETAIL_REQUEST = "LOAD_CAFE_DETAIL_REQUEST";
export const LOAD_CAFE_DETAIL_SUCCESS = "LOAD_CAFE_DETAIL_SUCCESS";
export const LOAD_CAFE_DETAIL_FAILURE = "LOAD_CAFE_DETAIL_FAILURE";
