export const CLICK_FILTER_CHECK_BOX = "CLICK_FILTER_CHECK_BOX";

// 필터링 결과 전송
export const SUBMIT_FILTERING_REQUEST = "SUBMIT_FILTERING_REQUEST";
export const SUBMIT_FILTERING_SUCCESS = "SUBMIT_FILTERING_SUCCESS";
export const SUBMIT_FILTERING_FAILURE = "SUBMIT_FILTERING_FAILURE";
